SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, "%Y-%m-%d") START_DATE, DATE_FORMAT(END_DATE, "%Y-%m-%d") END_DATE, if(DATEDIFF(END_DATE, START_DATE) >= 29, "장기 대여", "단기 대여") RENT_TYPE
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where DATE_FORMAT(START_DATE, "%Y-%m") = "2022-09"
order by 1 desc